============================================================
               DAY 9 (AUGUST 12) - INDEX
============================================================

1. Parent & Child Table Relationships (Foreign Key Enforcement)
   1.1 Destruction Rules Summary (Parent protection vs Child destruction)

2. Testing DELETE Operations
   2.1 Deleting Unreferenced Parent Rows (Success)
   2.2 Deleting Referenced Parent Rows (Reference Constraint Error)

3. Testing TRUNCATE Operations
   3.1 Attempting TRUNCATE on Referenced Parent Table (FK Error)

4. Testing DROP Operations
   4.1 Attempting DROP on Referenced Parent Table (FK Error)

============================================================
