============================================================
               DAY 3 (AUGUST 3) - INDEX
============================================================

1. Class Task - SQL Filtering Practice
   1.1 Question 1: Range & List Filtering (Salary NOT BETWEEN & dept IN)
   1.2 Question 2: Specific Character Length & Boundary Matching (LIKE 'A____n')
   1.3 Question 3: Substring Exclusion Filtering (Email NOT LIKE '%gmail%')
   1.4 Question 4: Case-Insensitive Vowel Detection in Employee Names
   1.5 Question 5: Alphanumeric Character Matching ([A-Za-z] AND [0-9])
   1.6 Question 6: Range Filtering without BETWEEN or LIKE (>= AND <=)

============================================================
